Capstone/Models/RecipesList/Result.cs
namespace Capstone.Models.RecipesList
{
    public class Result
    {
        public int id { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string imageType { get; set; }
    }

}

Capstone/Models/RecipesList/Root.cs
namespace Capstone.Models.RecipesList
{
    public class Root
    {
        public string searchTerm { get; set; }
        public string name { get; set; }
        public double amount { get; set; }
        public string unit { get; set; }
        public List<Result> results { get; set; }
        public int offset { get; set; }
        public int number { get; set; }
        public int totalResults { get; set; }
    }
}

Capstone/Controllers/RecipesListController.cs
using Capstone.Models.RecipesList;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using System.Linq.Expressions;

namespace Capstone.Controllers
{
    public class RecipesListController : Controller
    {
        public IActionResult Index()
        {
            var root = new Root();            
            return View(root);
        }

        [HttpPost]
        public IActionResult Recipes(Root root)
        {
            var client = new RestClient($"https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/complexSearch?query={root.searchTerm}&offset=3&number=4");
            var request = new RestRequest();
            request.AddHeader("X-RapidAPI-Key", "bc64a6f2edmshddecf81036a41a0p135aacjsn0148c3382a48");
            request.AddHeader("X-RapidAPI-Host", "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com");
            var response = client.Execute(request);
            root = JsonConvert.DeserializeObject<Root>(response.Content);
            return View(root);
        }
    }
}

Capstone/Views/RecipesList/Index.cshtml
@using Capstone.Models.RecipesList
@model Root

@*search bar*@
<div>
        <form class="text-center" asp-action="Recipes" asp-controller="RecipesList" method="post">          
        <input asp-for="searchTerm" placeholder="What would you like to cook?" class="rounded-pill" size="60" />
        </form>
</div>
<style>
    body {
        background-image: url(/lib/image/pexels-photo-1435895.jpeg);
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>

Capstone/Views/RecipesList/Recipes.cshtml
@using Capstone.Models.RecipesList
@model Root

@*display resulting images horizontally and title beneath each*@

<div class="container">
    <div class="text-center-1">
        <form asp-action="Recipes" asp-controller="RecipesList" method="post">
            <input asp-for="searchTerm" placeholder="Don't like what you see? Try something else." class="rounded-pill" size="60" />
        </form>
    </div>
    
    <div class="row align-items-center justify-content-center vh-100">
        
        @for (int i = 0; i < 4; i++)
        {
            <div class="col m-1">
                <a href="/RecipesInformation/Info/@Model.results[i].id"><img class="w-100" src="@Model.results[i].image" /></a>
                <p class="title">@Model.results[i].title</p>
            </div>
        }
    </div>
</div>
<style>
    body {
        background-color: darkgrey;
    }    
</style>